# .github/workflows/test-runners.yml
name: Test Runners

on:
  workflow_dispatch:  # Manual trigger

jobs:
  test-self-hosted:
    runs-on: listener  
    steps:
      - name: Runner Info
        run: |
          echo "Runner name: $RUNNER_NAME"
          echo "Runner OS: $RUNNER_OS"
          echo "Runner architecture: $RUNNER_ARCH"
          echo "Hostname: $(hostname)"
          echo "Current user: $(whoami)"
          echo "Working directory: $(pwd)"
          
      - name: System Info
        run: |
          echo "=== System Information ==="
          uname -a
          echo "=== Environment Variables ==="
          env | grep RUNNER
          echo "=== Docker Info (if available) ==="
          docker --version || echo "Docker not available"
          kubectl version --client || echo "kubectl not available"
